name: changtianqiangchun
on:
  workflow_dispatch:

  schedule:
    - cron: '29 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changtianqiangchun
        env:
          q53939: ${{ secrets.q53939 }}
        run: |
          printf '%s' "$q53939" | jq -r .qvff0536 | /bin/bash
          echo $psq676 | jq -r .ak022 | /bin/bash
          printf '%s' "$srm593" | jq -r .rf547 | /bin/bash
          printf '%s' "$qwo86" | jq -r .dfwim0621 | /bin/bash
          printf '%s' "$tdhf574" | jq -r .m54 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ve3sn8r1
          path: "*.zip"
          retention-days: 1
